name: CI
on: [push, pull_request]
jobs:
  build:
    name: Lint, Test, Build & Pack on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: c-hive/gha-npm-cache@v1

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build-ci

      - name: Pack
        run: npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: reduxjs-toolkit*.tgz

  test-dist:
    name: Test against dist
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['14.x']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: c-hive/gha-npm-cache@v1

      - name: Install deps
        run: npm ci --ignore-scripts

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Install build artifact
        run: |
          sed -i -e '/"name": "@reduxjs\/toolkit",/d' package.json
          npm i reduxjs-toolkit-*.tgz --ignore-scripts
          sed -i -e /@remap-prod-remove-line/d ./tsconfig.base.json ./jest.config.js ./src/tests/*.* ./src/query/tests/*.*

      - name: Run tests, against dist
        run: npm test

  test-types:
    name: Test Types with TypeScript ${{ matrix.ts }}

    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['14.x']
        ts: ['3.9', '4.0', '4.1', '4.2', '4.3', 'next']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: c-hive/gha-npm-cache@v1

      - name: Install deps
        run: npm ci --ignore-scripts

      - name: Install TypeScript ${{ matrix.ts }}
        run: npm install typescript@${{ matrix.ts }} --ignore-scripts

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Install build artifact
        run: |
          sed -i -e '/"name": "@reduxjs\/toolkit",/d' package.json
          npm i reduxjs-toolkit-*.tgz --ignore-scripts
          sed -i -e /@remap-prod-remove-line/d ./tsconfig.base.json ./jest.config.js ./src/tests/*.* ./src/query/tests/*.*

      - name: "@ts-ignore stuff that didn't exist pre-4.1 in the tests"
        if: ${{ matrix.ts < 4.1 }}
        run: sed -i -e 's/@pre41-ts-ignore/@ts-ignore/' -e  '/pre41-remove-start/,/pre41-remove-end/d' ./src/tests/*.* ./src/query/tests/*.ts*

      - name: Test types
        run: |
          ./node_modules/.bin/tsc --version
          npm run type-tests
